### ISSUE TITLE
Gwater doesn't work with this

### ISSUE THREAD

**Issue by TitaniumSpyBorgBear** [Joshua-Ashton/VPhysics-Jolt#64]
The water just falls through the floor with this.

**Comment by Joshua-Ashton** [comment]
Maybe @Mee12345 would have a starting point to go off here.

**Comment by Mee12345** [comment]
patch to https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/44 should fix this

**Comment by Joshua-Ashton** [comment]
There are development builds available here, maybe someone can test it? https://git.froggi.es/joshua/vphysics_jolt_gmod_builds

I am out for the weekend.

**Comment by TitaniumSpyBorgBear** [comment]
Hey so I just tested it out, here's what y'all did fix and it did work:
The standpose tool and ragdoll mover now work again

What is still broken:
Boats
Pulleys
Breakable constraints.

If I find anything else broken I'll tell you.

**Comment by TitaniumSpyBorgBear** [comment]
Oh right! Gwater is also still broken, still falling through the floor.

**Comment by nicbou0321** [comment]
> There are development builds available here, maybe someone can test it? https://git.froggi.es/joshua/vphysics_jolt_gmod_builds
> 
> I am out for the weekend.

is this some kind of sick joke? 
heres a website to try a dev build, cant see anything bc i gotta make an account, and account creation is disabled. 
GG stupid useless website. 
guess gwater is still broken with no way to try an alternative build bc the website is hella stupid and literally dont function. great job. guess ill go pound sand.
